### ISSUE TITLE
Potion ID config

### ISSUE THREAD

**Issue by dolandemort** [Solace7/EnhancedPortals#3]
The mod does not appear to obey its config option to set the potion effect ID. I have tried values under 32, but it always appears to be assigned to '0' (I believe the first unoccupied available potion ID) no matter what I put in the config.

This is all using "v3.0.13" in the releases section for 1.7.10.

**Comment by Solace7** [comment]
Looks like the configuration file wasn't being read properly. I've fixed and will release in a jiff.

**Comment by dolandemort** [comment]
Thanks for the prompt response. I had given up hope of using this mod in my modpack until I found your fork of it.

**Comment by Solace7** [comment]
After fixing all the bugs, my hope is to add new features too. You'll have to edit the config from the file unfortunately. I havent yet figured out how to fix the config gui.
